global:
  ## Альтернатива ограниченным yaml-алиасам Helm'а. Даёт возможность не дублировать одну и ту же конфигурацию много раз.
  #
  # Здесь, в "global._includes", объявляются блоки конфигурации, которые потом можно использовать в любых values-файлах.
  # Пример подтягивания этих блоков конфигурации в репозитории приложения:
  # -----------------------------------------------------------------------------------------------
  # .helm/values.yaml:
  # -----------------------------------------------------------------------------------------------
  # apps-cronjobs:
  #   cronjob-1:
  #     _include: ["apps-cronjobs-defaultCronJob"]
  #     backoffLimit: 1
  # -----------------------------------------------------------------------------------------------
  #
  # В примере выше конфигурация из include-блока "apps-cronjobs-defaultCronJob" развернётся на уровне
  # apps-cronjobs.cronjob-1, а потом поверх развернувшейся конфигурации применится параметр "backoffLimit: 1",
  # при необходимости перезаписав параметр "backoffLimit" из include-блока.
  #
  # Подробнее: https://github.com/flant/helm-charts/tree/master/.helm/charts/flant-lib#flexpandincludesinvalues-function
  _includes:
    # _include_from_file добавляет(инклудит) YAML из файла, работает в любом месте values.yaml
    _include_from_file: helm-apps-defaults.yaml


